package org.hni.user.om;

// Generated Apr 19, 2017 11:39:46 PM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UserStatus generated by hbm2java
 */
@Entity
@Table(name = "user_status")
public class UserStatus implements java.io.Serializable {

	private UserStatusId id;

	public UserStatus() {
	}

	public UserStatus(UserStatusId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "status", column = @Column(name = "status", nullable = false, length = 2)) })
	public UserStatusId getId() {
		return this.id;
	}

	public void setId(UserStatusId id) {
		this.id = id;
	}

}
